[tool.poetry]
name = "example"
version = "0.1.0"
description = "Test project"
authors = ["Test Author <author@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25"
pandas = "^1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
